# For more info on HTTP files go to https://aka.ms/vs/httpfile

@hostname=localhost
@port=5128

# Pet APIS
## POST /api/pets
## GET /api/pets
## GET /api/pets/{name}
## PUT /api/pets/{name}
## DELETE /api/pets/{name}

## 1. Create Pet
POST http://{{hostname}}:{{port}}/api/pets
Content-Type: application/json; charset=utf-8

{
    "Name": "Snowball",
    "Type": "Cat",
    "Color":"White",
    "Price": 99
}

## Response 
### 1.Created, Return the Pet created with Status Created ( 201 )
### 2.Already Existed, Return Status Bad Request ( 400 )

## 2. Get Pet By Name
GET http://{{hostname}}:{{port}}/api/pets/Snowball
###  1.Found, Return the Pet found with Status OK ( 200 )
###  2.Not Found, Return Status Not Found ( 404 )

## 3. Get All Pets
GET http://{{hostname}}:{{port}}/api/pets

## Response  
### 1.Found, Return all Pets found with Status OK ( 200 )

## 4. DELETE the Pet by Name
DELETE http://{{hostname}}:{{port}}/api/pets/Snowball

## Response  
### 1.Deleted, Return all Pets found with Status NO CONTENT ( 204 )
### 2.Not Found, Return Status Not Found ( 404 )

## 5. PUT Update Price of the Pet
PUT http://{{hostname}}:{{port}}/api/pets/Snowball
Content-Type: application/json; charset=utf-8

{
    "Price": 101
}

## Response  
## 1.Updated,  Return the Pet updated with Status OK ( 200 )
## 2.Not Found, Return Status Not Found ( 404 )